server:
  port: 18782

spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    database: 0
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: config-bus-server
          uri: lb://CONFIG-BUS-SERVER
          predicates:
            - Path=/yml/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8891/eureka