spring:
  application:
    name: hystrix-turbine
  profiles:
    active: dev
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
turbine:
  aggregator:
    cluster-config: default
  app-config: tristeza-cloud-order
  cluster-name-expression: '"default"'
  combine-host-port: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream