spring:
  application:
    name: eureka-server
  profiles:
    active: dev
server:
  port: 8891
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost