############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: dev
  redis:
    password: 123456
    cluster:
      nodes: 172.16.16.14:6379,172.16.16.15:6379,172.16.16.16:6379,172.16.16.17:6379,172.16.16.18:6379,172.16.16.19:6379
  datasource:
    url: jdbc:mysql://localhost:3306/distribute?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123abcABC # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 #上传文件大小上线
      max-request-size: 512000

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.tristeza.distributedlocks.mysql.model   # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl