server:
  port: 28999

spring:
  application:
    name: sleuth-b
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:18899

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8891/eureka