############################################################
#
# 配置数据源信息
#
############################################################
spring:
  application:
    name: tristeza-cloud-cart
  profiles:
    active: dev