############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 10003
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"