############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/chloe?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123abcABC
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
#  session:
#    store-type: redis